### ISSUE TITLE
IET NG Thunderbird 78 Update - Release/Tasks

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#143]
It's under review!
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.0/xpi/import-export-tools-ng-10.0.0-tb.xpi

Track Conversion/Beta Here:

Current Beta:  
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.0/xpi/import-export-tools-ng-10.0.0-b15-tb.xpi

Status:
- fix EML import, hotkeys
- runs in both 68 and 78
- Backup fixes
- fixed profile import
- fixed backup spiritual
- basic testing
- all locales fixed
- fixed mboxdialog ( reference,cancel)
- fixed menus
- various bug fixes

Current Work:

Initial Tasks:

- [x] - Branch, tracking issue - 5m
- [x] - Update build scripts - 2m
- [x] - Reread WindowListenerAPI, download - 10m
- [x] - Fix versions - 1m

Main Conversion Tasks:

- [x]  Inspect/convert chrome.manifest - 4m
- [x]  Inspect/convert manifest.json - 2m
- [x]  create overlay loaders - 4h
- [x]  fixup references - 1h
- [x]  basic checks - 3h
- [x]  b1 post - first past basic  running

- [x]  Add missing Greek locale files
- [x]  fix help files for references
- [x]  b2 post - most functionality spot checked 

- [x]  identify possible' bug candidates
- [x]   #118 - stream signature change for plaintext
- [x]   #77 - use global settings for PDF
- [x]   #57 - open files error 
- [x]  Fix menus:
- [x]  Post b3
- [x]  Post b4 - fixed dialog
 
- [x] #129 - PDF header/footer with custom date
- [x] Post b5 - fixes multiple selected PDFs, profile import not working

- [x] remove SMS stuff
- [x]  fix profile import/export
- [x] Post b6

- [#]  #119 sender/recipient tokens
- [x]  check/fix localized help
- [x] autobackup dialogue fixed
- [x] - Post b7
- [x] -  Post b8 - 78 backup fixes
- [x] - Post b9 - status message fixes, basic tests Linux, OS X 
- [x] - Post b10 - fix #134 , options submenu 68
- [x] - Post b11 - multiple issues
- [x] - Post b12 - backup,empty tokens, cleanup, 90% tested (Windows 10)
- [x] - Post b13 - add index date format to UI, 'none' in index for 
- [x]  - Post b14 - hotkeys, EML
- [x]  - Post b15 - fix attachment export issue
- [x]  - Post b16 - add changes
- [x]  - Post v10.0.0 - release 

Cleanup/Release Tasks:
- [x]  start top to bottom testing
- [x]  update change log
- [x]  post to review

**Comment by kunalbedi** [comment]
Cannot wait for you to update the release.

Thank you for the prompt action on this one.
Most appreciated.

Regards
Kunal Bedi

**Comment by cleidigh** [comment]
@kunalbedi 
first pass just posted

**Comment by kunalbedi** [comment]
@cleidigh Thank you for the quick turnaround. I am so humbled and impressed.
I installed the beta file and it is working as my needs are. I have not throughly tested but it did export my messages as EML format as I wanted and as it used to.

My thunderbird: 78.2.1 (32-bit)

I can confirm that the menu on right click on folders appears for the plugin and that the option **"Export äll messages in folder > EML format"** works as it should.

Thank you very much Christopher. 

Regards
Kunal Bedi

**Comment by rphair** [comment]
@cleidigh thanks also from here... I realise what a hindrance it is to my workflow to be without this extension and am very grateful for your work.

FYI (on Ubuntu 18.04 / Tbird 78.2.1) we weren't told a restart was required after installing the extension, but we didn't see any of the extension's menu selections or folder & email context menus until after restarting Thunderbird.

**Comment by cleidigh** [comment]
@rphair 
Thanks. any output in the Debug log ?
I will see what 68 on my VM does
I do not have 78 I will probably create a separate VM 
Christopher

**Comment by rphair** [comment]
I'll have a look if you tell me where or what pathname to check... as far as I can tell it's working normally except that an advisement to restart Tbird might be appropriate if it still behaves that way upon official release. :)

**Comment by cleidigh** [comment]
now I am a bit confused.  
I understood from your post above that you did not see any of the menus installed even after restarting.
now as I understand it once you did  restart you get the menus and the functionality that you try works, yes?
I also just confirmed it works on        Mint 18 with Thunderbird 68
I will have to check if there is any reason you had to restart. maybe first install?
Christopher

**Comment by ferthalangur** [comment]
Greetings,

I just attempted to install import-export-tools-ng-10.0.0.b4-tb.xpi into Thunderbird 78.2.1 and the message I receive is 

**mozapps** The add-on downloaded from this site could not be installed because it appears to be corrupt.

I am running on MacOS 10.15.6

Any ideas what I'm doing wrong?

_rob_

**Comment by cleidigh** [comment]
@ferthalangur 
I was able to do a couple of tests. I have two systems El Capitan and Mojave
I have to do everything remotely by voice being disabled so I am rather limited
on anything other than Windows.
the extension works on El Capitan , 'but I can confirm it does not install on Mojave
I do not even get anything meaningful error wise
I also tried another extension with the same results
I am thinking that the OS X Thunderbird 78 has some issues
I will try and investigate, however I don't want to delay if it's out of my control
Christopher

**Comment by cleidigh** [comment]
@ferthalangur 
sounds good
the xpi file is just a zip format if you unzip it you will see various JavaScript and other files
Christopher

**Comment by ferthalangur** [comment]
OK ... this looks like user error.  I should have clicked on the link, and then from the page that it links to, click on the **Download** button.  Instead,  I used **Save Link As** on that link ... which works fine if the URL is for a binary file ... but downloaded the HTML file of the "blob" page in this case ... into a file named import-export-tools-ng-10.0.0.b4-tb.xpi . 

Once I successfully downloaded the .xpi file, Thunderbird loaded it without complaint into 78.2.1 (64 bit) in MacOS Catalina.

**Comment by cleidigh** [comment]
great
do you get the menus, trying anything yet?
I could not load it

**Comment by ferthalangur** [comment]
It loaded up fine. 
- All four export folder functions work as expected on a single (complex multi-layered) folder of folders of old - I selected several folders and ran "Export all messages in the folder" in EML format, and it did what was expected. What I did not expect, although I have not read the documentation or used it before, so this may be expected behavior, is that each folder name was suffixed with a date and time stamp.

**Comment by ferthalangur** [comment]
Found a problem ... I selected a folder, then mouse right on ImportExportToolsNG -> Search and Export ...

A small, scrunched-up message / error box appears with the following message when expanded:

![Problem_loading_page_and_gmail_inbox_-_Local_Folders](https://user-images.githubusercontent.com/5349295/92305512-182c3e00-ef56-11ea-863a-51c813314287.jpg)

Something did not get bundled into the .xpi file?

**Comment by cleidigh** [comment]
@ferthalangur 
thanks for the catch!
yes, I missed converting the extension on this dialog
it will be fixed in b5 as well as a big issue with multiple selected PDF messages
Christopher

**Comment by DrStrange** [comment]
Import Profile not working yet?- 
Buttons at the bottom not labelled. Clicking Options on each page -Path of the profile to import, start import, run the Profile Manager - nothing happens.
Export Profile appears to work, I created another profile using profile manager, copied files from  IET ToolsNG exported profile folder into this new profile folder, selected the new profile, no problems.
Thanks for getting this working with Thunderbird 78. I use Windows 8.1

**Comment by cleidigh** [comment]
@DrStrange 
Thanks !
good chance there are some issues, still wrestling but other stuff, about to post b5
might be able to check this out before, but I don't want to wait too long since
b5 deals with several other issues
Christopher

**Comment by cleidigh** [comment]
@DrStrange
b5 does not fix it, more complicated unfortunately

**Comment by cleidigh** [comment]
@DrStrange 
Try b6 import wizard fixed as well as export

**Comment by terodev** [comment]
Hello @cleidigh and thanks a lot for all the efforts you've put to this add-on.

I've got a .mbox file that represents an account at the hey.com service, and I tried to import it using the b6 build and got the following error:

```
Uncaught TypeError: tempfolder.Delete is not a function  mboximport.js:431:13
    trytocopy chrome://mboximport/content/mboximport/mboximport.js:431
    importmbox chrome://mboximport/content/mboximport/mboximport.js:628
```

Not a single message appears, only an empty folder named after the input file appears once I've restarted Thunderbird.

I'm running version 78.2.1 on my macOS Catalina 10.15.6.

Do you have any idea what could be wrong?

**Comment by DrStrange** [comment]
@cleidigh,
Thanks for b6,  fixes import wizard.
I notice however one issue with b6 (and I think I remember it was also an issue in b4) -  when closing TB 78.2.1 I get a very tiny window which appears, entitled "problem loading page". It is so tiny all it has is a close button and a line underneath the title. It appears everytime I close TB. If  I disable IET NG, the windows does not appear.
![Capture](https://user-images.githubusercontent.com/443688/92515432-82b9d400-f20b-11ea-8c85-cdf22f57591a.JPG)
 NG and

**Comment by cleidigh** [comment]
@terodev 
where did the m box file come from ? some have different  formats that are not compatible
if you could post a portion of the file that would help
question

**Comment by cleidigh** [comment]
@DrStrange 
I just saw this for the first time when I enabled backup for testing.
Do you have completely enabled?
@cleidigh

**Comment by cleidigh** [comment]
b7 restores backup dialogue

**Comment by kunalbedi** [comment]
@cleidigh First of all thanks.
Is it just me or I am missing the status bar updates when things are getting exported.
I used to get 1 of 70 messages exported (if I remember correctly) when things were being exported etc. in my status bar.

Now I get none.

Please check if I am hallucinating or misremembering this feature.

**Comment by cleidigh** [comment]
@kunalbedi 
Hallucinating of course!
the status bar was broken until recently
what version are you on?
I just posted b8
definitely issues on OSX /78
I think next all the status messages but it's possible I missed something, I'm still working on higher-level stuff
Christopher

**Comment by kunalbedi** [comment]
@cleidigh Great and I am 7 beta versions behind.

Thank you. Installing the new beta and will get back.

Thanks 👍

**Comment by kunalbedi** [comment]
@cleidigh 
Updated to b8.
Status messages are back. Yipee!!!

BUT https://www.screencast.com/t/kPMKfPAY

this message above stays on the status bar after successful export. 
The Stop button also works if clicked . This should not be the case.

Please do check when you have time for this minor niggle.

I am on Thunderbird 78.2.1 (32-bit) on Win 10

Regards
Kunal Bedi

**Comment by DrStrange** [comment]
@cleidigh 
The extra window bug no longer appears with b8.
Thanks!

**Comment by terodev** [comment]
> where did the m box file come from ? some have different formats that are not compatible

This particular file was created by hey.com when one chooses Export Data from the main menu. I also tried to import several .mbox files created by ProtonMail import-export tool, but got the very same error.

> if you could post a portion of the file that would help

I'll have a further look of the file and see if I could provide a sample for you.

**Comment by cleidigh** [comment]
@terodev 
Also check out the ConsoleOutput ( Shift control J)
you can Copy and post here
what sequence of commands are you using?

**Comment by cleidigh** [comment]
@kunalbedi 
so far I cannot find which export operation makes the status text rename.
there is a preference,
extensions.importexporttoolsng.delay.clean_statusbar
that defaults to 5000 === 5s
if this somehow got set zero
the messages remain
@cleidigh

**Comment by cleidigh** [comment]
@kunalbedi 
I found what I missed
check out b9

**Comment by kunalbedi** [comment]
@cleidigh I just installed b9 and I see that it is working I guess.
I will try some more and give a definitive answer soon.
Thanks, Christopher for such a fast turn around. You are an inspiration.

**Comment by cleidigh** [comment]
All
anymore Feedback?
I'm trying to decide to release
thanks
Christopher

**Comment by slrslr** [comment]
> anymore Feedback?

Sorry for OT? so i have downloaded 10.0.0 b9 from https://github.com/thundernest/import-export-tools-ng/blob/v10.0.0/xpi/ and then drag & drop the file to the Thunderbird extensions section, enabled it and in the Import tool, Import exerything, it says No application to import data from. Mail only import shows Becky and outlook where it is unable to find mail.

**Comment by cleidigh** [comment]
@slrslr 
first best to get the latest: b13 at the moment, I always have a link to the latest beta for the top of the thread.
you are looking at the internal import export, not the extension functionality.  you used various contexts when used to access to import-export functions.  There is also localized  help built-in:  one way you can get to the functionality as well as help: Tools/ ImportExportTools NG help us at the bottom of the menu and that describes almost menu functions.
Christopher

**Comment by slrslr** [comment]
@cleidigh 
i am confused. You suggest i should use internal import tool and not the extension functionality, but i that is what i believe i already tried - Main Thunderbird menu button / Tools / Import... and i see what i mention in my previous comment: "Import exerything, it says No application to import data from. Mail only import shows Becky and outlook where it is unable to find mail."
In Addons/Extensions/IET NG section i do no see any importing possibility. b13 and Thunderbird 78.2.1 (64-bit)

**Comment by cleidigh** [comment]
@slrslr 
Sorry for the confusion, lousy dictation..
What I meant was that the dialogue you were looking at that includes Becky is Thunderbird 's import capability not the extension.
the extensions install several Menus under Tools, the message context menu, the folder context menu and the search dialogue.  below I show the tools menu with the help option highlighted
if you go to help which is totally localized list all of the functions.
there has always been little help, I have been trying to improve that
let me know if this helps
Christopher
![image](https://user-images.githubusercontent.com/25272315/93688104-5ca8f500-fa91-11ea-890c-8dd115024775.png)

**Comment by slrslr** [comment]
Thank you, indeed. I have not seen that top menu on the image. Possibly hidden by default :-S I had to right click the top bar and select the "Menu bar" to display. I expected there will be only one Tools menu :)
![thunderbird-tools-menu](https://user-images.githubusercontent.com/6596726/93689799-8ed24b00-fac1-11ea-8053-195005d5ebd5.gif)

So i selected the import method

and it started. Several times complained about:
```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: chrome://mboximport/content/mboximport/mboximport.js:1086
```
So i ticked the box to mute it in future.
Unfortunately i am having issue Thunderbird (had same with Firefox previously) where the Thunderbird shows in Windows 10 taskbar on the bottom, but clicking it does nothing, so i had to close TB after its CPU utilization ceased (after import complete) without seeing result.

After starting it again, it appears that the import worked, e-mail that i opened is readable.

**Comment by terodev** [comment]
@cleidigh I can confirm that with the b14 I'm able to import .mbox files again - thank you :)

**Comment by andystyl** [comment]
Installed beta version and worked like a charm, exported, and imported on 2 different PCs both with thunderbird v78.
Thank you for saving me.

**Comment by cleidigh** [comment]
@andystyl 
Great! thanks
I believe b16 Can hopefully be released by the end of this weekend
hopefully a few more people will try b15
Christopher

**Comment by kunalbedi** [comment]
Am working with b15 and can confirm that it is working perfectly for my use case.

Thanks for everything.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by cleidigh** [comment]
@kunalbedi 
Thanks! would you mind just letting me know your OS and use cases just so I have a better understanding
of various things people  tested
if all goes well I will post the release to the queue today.
@cleidigh

**Comment by kunalbedi** [comment]
Hi @cleidigh<https://github.com/cleidigh>

My OS is Windows 10 Pro 10.01.19041 Build 19041

Thunderbird 78.2.2 (32 bit)

Regards
Kunal Bedi


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kunalbedi** [comment]
Congrats @cleidigh ,

For putting the final version of the review.

Just one thing as I am not much aware of the process.

Will the beta I have automatically update to the final release or I have to jump through some hoops once it is in action?

Regards
Kunal Bedi

**Comment by cleidigh** [comment]
@kunalbedi 
Thanks
to be honest I am not sure ,if it does automatically upgrade, try to check for updates button
otherwise uninstall and install from ATN
Christopher

**Comment by lucknaumann** [comment]
@cleidigh Thanks for this great add-on!
@kunalbedi I just tried it and it didn't auto-update. Went to the Thunderbird Add-on page (in Thunderbird, right after it updated to 78.3.1 (64-bit)) and installed from there. I'm on Windows 10.

**Comment by cleidigh** [comment]
@lucknaumann 
@kunalbedi 
Thanks 
I just tried checking for updates (starting with beta installed) - does not recognize updating
 installed "official" 4.1.0 then recognized there was an update
clearly when you are using an unreleased version you are out of the update loop
@cleidigh

**Comment by cleidigh** [comment]
All beta users:

if you have installed any beta you will have to install the official version manually.
Christopher

**Comment by kunalbedi** [comment]
@cleidigh 
Thanks a lot!!!

You are a gem.

**Comment by Sytten** [comment]
Any plan to support Thunderbird 82? I can't seem to install it on the latest beta.

**Comment by cleidigh** [comment]
@Sytten 
yes, just not sure when, several other 78 conversions I have to dear
Christopher
