### ISSUE TITLE
TB68 Update - Item Tracking

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#3]
Update Items:

- [x] Reformat js files - LF/Tab-4/basic Visual Studio code rules
- [x] Reformat XUL files

- [x] Add basic manifest.json @cleidigh 
- [x] First CSS fixup
- [x] Menu installs
  - [x]   Tools (add on options)
  - [x]   Tools (main menu)
  - [x]   Account pop-up
  - [x]   Folder Pop-up
  - [x]   search overlay
  - [ ]   messages pop up

- [ ] Menu Functions
  - [x]   Tools (add on options)
      menu installed, opens options dialog - visually okay with CSS fix
  - [x]   Tools (main menu)
  - [x]   Account pop-up
  - [x]   Folder Pop-up

- [x] Overlay updates
   - [x] Use messenger.xul for mboximport.xul in chrome.manifest
   - [x] Add HTML namespace to all XUL files
   - [x] Remove in-line scripts
   - [x] Verify scripts can run after overlay
   - [x] Remove stringbundles - load in JavaScript
   - [x] groupbox / label changes
   - [x] progressmeter => html:progress changes

**Comment by cleidigh** [comment]
All items tested except
SMS
Release: 4.0.0
